name: cannot_qiandao
description: "没必要签到APP，安工大第三方签到APP"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.5
  mmkv: ^2.0.1
  quick_actions: ^1.0.8
  dynamic_color: ^1.7.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  toml: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
